# Generated by Django 4.0.3 on 2022-04-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
